LittlerootTown_WeatherInstitute_2F_MapScripts::
	.byte 0
LittlerootTown_WeatherInstitute_2F_EventScript_BigWindow:: @ 81FA4C4
	msgbox LittlerootTown_WeatherInstitute_2F_Text_BeautifulView, MSGBOX_SIGN
	end

LittlerootTown_WeatherInstitute_2F_EventScript_SmallWindow:: @ 81FA4C4
	msgbox LittlerootTown_WeatherInstitute_2F_Text_WindowLight, MSGBOX_SIGN
	end

LittlerootTown_WeatherInstitute_2F_EventScript_ShipTable:: @ 81FA4C4
	msgbox LittlerootTown_WeatherInstitute_2F_Text_ShipPlans, MSGBOX_SIGN
	end
LittlerootTown_WeatherInstitute_2F_EventScript_RocketTable:: @ 81FA4C4
	msgbox LittlerootTown_WeatherInstitute_2F_Text_RocketPlans, MSGBOX_SIGN
	end
LittlerootTown_WeatherInstitute_2F_EventScript_WeatherTable:: @ 81FA4C4
	msgbox LittlerootTown_WeatherInstitute_2F_Text_WeatherPlans, MSGBOX_SIGN
	end
LittlerootTown_WeatherInstitute_2F_EventScript_OddTable:: @ 81FA4C4
	msgbox LittlerootTown_WeatherInstitute_2F_Text_ConfusingPlans, MSGBOX_SIGN
	end
LittlerootTown_WeatherInstitute_2F_EventScript_Barometer:: @ 81FA4C4
	msgbox LittlerootTown_WeatherInstitute_2F_Text_AirPressure, MSGBOX_SIGN
	end
LittlerootTown_WeatherInstitute_2F_EventScript_BreakTable:: @ 81FA4C4
	msgbox LittlerootTown_WeatherInstitute_2F_Text_CoffeeSpills, MSGBOX_SIGN
	end


LittlerootTown_WeatherInstitute_2F_Text_AirPressure: @ 81FB124
	.string "A barometer. \p"
	.string "It measures atmospheric pressure \n"
	.string "to predict the weather.$"

LittlerootTown_WeatherInstitute_2F_Text_CoffeeSpills: @ 81FB124
	.string "A table covered in \n"
	.string "rings and coffee stains. \p"
	.string "They should get some coasters!$"
LittlerootTown_WeatherInstitute_2F_Text_ConfusingPlans: @ 81FB124
	.string "Plans for some kind of device. \p"
	.string "You can't make \n"
	.string "heads or tails of it.$"
LittlerootTown_WeatherInstitute_2F_Text_WeatherPlans: @ 81FB124
	.string "Plans for some kind of device. \p"
	.string "It seems intended to \n"
	.string "influence the weather.$"
LittlerootTown_WeatherInstitute_2F_Text_RocketPlans: @ 81FB124
	.string "Plans for some kind of rocket. \p"
	.string "What would it be like in space?\n"
	.string "The ship looks uncomfortable.$"

LittlerootTown_WeatherInstitute_2F_Text_BeautifulView: @ 81FB124
	.string "It's even nicer from higher up!$"

LittlerootTown_WeatherInstitute_2F_Text_WindowLight: @ 81FB124
	.string "Not much to see, but \n"
	.string "it's nice to have natural light in here.$"


LittlerootTown_WeatherInstitute_2F_Text_ShipPlans: @ 81FB124
	.string "Plans for some kind of ship. \p"
	.string "It seems to be shaped to \n"
	.string "pierce through ice.$"



